### ISSUE TITLE
need to import some framework?

### ISSUE THREAD

**Issue by marco318** [globchastyy/SwiftUIImageEffects#5]
your example project has a trouble with build in iOS SDK 8.3 & xCode 6.3

I'm new in Swift , don't know about why this error occur.
This is just a report.

Thanks in advance.

![2015-04-13 8 48 52](https://cloud.githubusercontent.com/assets/1731778/7115008/89d65db0-e21e-11e4-99d7-847e29b0951b.png)

**Comment by ushisantoasobu** [comment]
@marco318 
i made PR about this.
https://github.com/ushisantoasobu/SwiftUIImageEffects/commit/dd5428109d4a35a3ac715cf493801c0b86c8ff71
